const Languages = {
  en: {
    size: 'Size',
    select_option: 'Select Options',
    add_order: 'Add to Order',
    view_basket: 'View Basket',
    checkout: 'Checkout',
    table_num: 'Table Number',
    confirm_order: 'Confirm Order',
    popup_details:
      'By placing this order you agree that you are present in Kings Arms and over 18 years old. ',
    place_order: 'Place Order',
    cancel: 'Cancel',
    add_notes: 'Add Notes:',
    total_bill: 'Total Bill',
    item: 'ITEM',
    order_confirmed: 'Order Confirmed',
    ordered_items: 'Ordered Items',
    back_to_menu: 'Back To Menu',
    currency: '$',
  },
  es: {
    size: 'Talla',
    select_option: 'Seleccione opciones',
    add_order: 'Agregar a la orden',
    view_basket: 'Viendo Basquet',
    checkout: 'Verificar',
    table_num: 'Número de mesa',
    confirm_order: 'Confirmar pedido',
    popup_details:
      'Al realizar este pedido, acepta que está presente en Kings Arms y es mayor de 18 años.',
    place_order: 'Reali pedido',
    cancel: 'Cancelar',
    add_notes: 'Agregar notas:',
    total_bill: 'Cuenta total',
    item: 'Articulo',
    order_confirmed: 'orden confirmada',
    ordered_items: 'Artículos pedidos',
    back_to_menu: 'Volver al menú',
    currency: '£',
  },
  fr: {
    size: 'Talli',
    select_option: 'Sélectionnez les options',
    add_order: 'Ajouter à la commande',
    view_basket: 'Voir le panier',
    checkout: 'Vérifier',
    table_num: 'Numéro de table',
    confirm_order: 'Confirmer la commande',
    popup_details:
      'En passant cette commande, présent Kings Arms et que vous ayez plus de 18 ans.',
    place_order: 'Pass comman',
    cancel: 'Annule',
    add_notes: 'Ajouter des notes:',
    total_bill: 'Facture totale',
    item: 'Objet',
    order_confirmed: 'Commande confirmée',
    ordered_items: 'Articles commandés',
    back_to_menu: 'Retour au menu',
    currency: '£',
  },
};

export default Languages;
